# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@main
        with:
          token: ${{ secrets.SECRET_TOKEN }}
      - name: Test the workflow
        run: |
         mkdir test
         cd test
         git init
         git remote add origin https://testliomandeep:${{ secrets.SECRET_TOKEN }}@github.com/testliomandeep/mytestrepo.git
         git fetch origin main
         git checkout main
         ls
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: testliomandeep/mytestrepo
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install node
        run: npm install

      - name: run build
        run: npm run build --if-present
      - name: start Test
        run: npm test -- --executiontype=web --provider=local --browser=chrome --allureResults='./allure-results'
